apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: odoo:17
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: timescaledb
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: db-password
          volumeMounts:
            - name: odoo-addons
              mountPath: /mnt/extra-addons
            - name: odoo-config
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
      volumes:
        - name: odoo-addons
          hostPath:
            path: /app/mes/odoo/addons
        - name: odoo-config
          configMap:
            name: odoo-config
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: factory
spec:
  selector:
    app: odoo
  ports:
    - port: 8069
